name = "Certificates"
license = "MIT"
description = "Certificates for MakerViet events"
tags = ["blog", "multilingual", "bootstrap"]
features = ["blog", "responsive", "Google Analytics", "bootstrap", "multilingual", "i18n"]
min_version = 0.56

[author]
  name = "Viet Anh Nguyen"
  homepage = "https://aicurious.io/"